services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432
      APP_HOST: localhost:3000
      RAILS_ENV: production
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_data: {}
